# Generated by Django 5.2.4 on 2025-07-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='IMAGES/Employe_profile/')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('Python', 'Python'), ('React', 'React'), ('Node.js', 'Node.js'), ('Asp.net', 'Asp.net')], max_length=255)),
            ],
        ),
    ]
