# Generated by Django 5.2.4 on 2025-07-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_city_country_employe_city_employe_country_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='country',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='state',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
